### ISSUE TITLE
less 汇总

### ISSUE THREAD

**Issue by dddreee** [dddreee/blog#8]
### tips
- 在缩写的css样式的时候， `/` 符号会被 `LESS` 当作除号去运算。可以写成 `~"/"` 阻止 `LESS` 的处理。如下
```less
.box{
 border: 11px / 22px;
}
// 编译后
.box { border: 0.5px }

// 写成 ~"/"
.box { border: 11px ~"/" 22px }
// => 
.box { border: 11px / 22px }
```

##
### Variables 变量声明
```less
@width: 10px;
@height: @width + 10px
```
